#### Análise dos casos de COVID19 no Brasil

Esse é um projeto colaborativo entre Hugo Fitipaldi e Daniel Fitipadi para a analise de dados da Pandemia de COVID19 no Brasil.

In [85]:
# Primeiro vamos ler as libraries que precisamos pro projeto

import pandas as pd
import numpy as np
import os
import time

Ok, a primeira coisa que temos fazer é criar uma função para fazer o download dos dados que vamos precisar

In [86]:
# Vamos começar com os dados do Governo Federal

def download_file(url = "https://mobileapps.saude.gov.br/esus-vepi/files/unAFkcaNDeXajurGB7LChj8SgQYS2ptm/b350824dbfad17f083e62d4b41e88cb7_Download_COVID19_20200408.csv",
                  filename = 'covid19_gov.csv'):
    ''' Essa função faz o download dos dados direto do link do Ministério da Saúde '''
    # primeiro checamos se o arquivo já existe
    if not os.path.isfile(filename):
        print('Downloading File')
        response = requests.get(url)
        # Check if the response is ok (200)
        if response.status_code == 200:
            # Open file and write the content
            with open(filename, 'wb') as file:
                # A chunk of 128 bytes
                for chunk in response:
                    file.write(chunk)
    else:
        print('File exists')
        
# Agora uma função para fazer o update dos dados se o baixamos a mais de meia hora        
def update_gov(filepath = 'covid19_gov.csv'):

    if os.path.isfile(filepath):
        sec = time.time() - os.path.getmtime(filepath)
        minutes = int(seconds) / 60 # 120 minutes
        hours = minutes / 60 # 2 hours
        
        if hours > 0.5:
            print('File is old, lets download it again')
            os.remove(filepath)
            download_file()
        
    if not os.path.isfile(filepath):
        download_file()
    
    else:
        print("Your file is pretty new")

update_gov()

Your file is pretty new

Agora é hora de checar os dados do governo e a estrutura em geral

In [87]:
# Primeiro vamos importar os dados
covid19_gov = pd.read_csv('covid19_gov.csv', sep=';', 
                        encoding='latin-1')
covid19_gov.head()

,região,sigla,date,casosNovos,casosAcumulados,obitosNovos,obitosAcumulados
0,Norte,RO,30/01/2020,0,0,0,0
1,Norte,RO,31/01/2020,0,0,0,0
2,Norte,RO,01/02/2020,0,0,0,0
3,Norte,RO,02/02/2020,0,0,0,0
4,Norte,RO,03/02/2020,0,0,0,0

In [88]:
covid19_gov.columns = ["Regiao", "Sigla", "Data",
                      "Casos_novos", "Casos_acumulados",
                      "Obitos_novos", "Obitos_Acumulados"]
covid19_gov.head()

,Regiao,Sigla,Data,Casos_novos,Casos_acumulados,Obitos_novos,Obitos_Acumulados
0,Norte,RO,30/01/2020,0,0,0,0
1,Norte,RO,31/01/2020,0,0,0,0
2,Norte,RO,01/02/2020,0,0,0,0
3,Norte,RO,02/02/2020,0,0,0,0
4,Norte,RO,03/02/2020,0,0,0,0

In [89]:
covid19_gov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Regiao             1890 non-null   object
 1   Sigla              1890 non-null   object
 2   Data               1890 non-null   object
 3   Casos_novos        1890 non-null   int64
 4   Casos_acumulados   1890 non-null   int64
 5   Obitos_novos       1890 non-null   int64
 6   Obitos_Acumulados  1890 non-null   int64
dtypes: int64(4), object(3)
memory usage: 103.5+ KB

In [92]:
covid19_gov['Data'] = pd.to_datetime(covid19_gov['Data'])
print(covid19_gov.info())
covid19_gov.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Regiao             1890 non-null   object
 1   Sigla              1890 non-null   object
 2   Data               1890 non-null   datetime64[ns]
 3   Casos_novos        1890 non-null   int64
 4   Casos_acumulados   1890 non-null   int64
 5   Obitos_novos       1890 non-null   int64
 6   Obitos_Acumulados  1890 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 103.5+ KB
None

,Regiao,Sigla,Data,Casos_novos,Casos_acumulados,Obitos_novos,Obitos_Acumulados
0,Norte,RO,2020-01-30,0,0,0,0
1,Norte,RO,2020-01-31,0,0,0,0
2,Norte,RO,2020-01-02,0,0,0,0
3,Norte,RO,2020-02-02,0,0,0,0
4,Norte,RO,2020-03-02,0,0,0,0

In [93]:
covid19_gov.Sigla.value_counts()

RN    70
RS    70
MS    70
MA    70
AM    70
RR    70
CE    70
AL    70
BA    70
PA    70
MT    70
MG    70
AC    70
ES    70
SP    70
RJ    70
GO    70
SC    70
RO    70
SE    70
DF    70
AP    70
PI    70
PE    70
PR    70
PB    70
TO    70
Name: Sigla, dtype: int64